name: Update Derech Olam Name to Mishkan

on:
  workflow_dispatch:

jobs:
  update-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Update Script
        env:
          GITHUB_PAT: ${{ secrets.DOMG6027_UPDATE_TEMP }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: node updateName.js
